#!/bin/bash

# RAFT Cluster Virtual Network Setup Script
# Creates isolated network namespaces for NSO RAFT cluster testing

set -euo pipefail

# Script metadata
SCRIPT_NAME="raft-cluster-netns.sh"
SCRIPT_VERSION="1.0.0"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Default configuration
DEFAULT_NODES=3
DEFAULT_PREFIX="ha"
DEFAULT_WORK_DIR="$(pwd)"
DEFAULT_CLUSTER_NAME="test-cluster"
DEFAULT_NETWORK_PREFIX="192.168"
DEFAULT_BRIDGE_NAME="ha-cluster"
DEFAULT_SSL_ENABLED="false"
DEFAULT_TIMEOUT=30
DEFAULT_CONFIG_FILE=".raft-cluster.conf"

# Global variables
NODES="${DEFAULT_NODES}"
PREFIX="${DEFAULT_PREFIX}"
WORK_DIR="${DEFAULT_WORK_DIR}"
CLUSTER_NAME="${DEFAULT_CLUSTER_NAME}"
NETWORK_PREFIX="${DEFAULT_NETWORK_PREFIX}"
BRIDGE_NAME="${DEFAULT_BRIDGE_NAME}"
SSL_ENABLED="${DEFAULT_SSL_ENABLED}"
SSL_CERT_DIR=""
NCS_FLAGS=""
VERBOSE=false
DRY_RUN=false
FORCE=false
KEEP_CONFIG=false
TIMEOUT="${DEFAULT_TIMEOUT}"
SPECIFIC_NODE=""
NO_NSO=false
HOST="localhost.localdomain"
CONFIG_FILE=""
ENV_SH_PATH=""

# Configure command options
AUTO_GENERATE=false
CONFIG_OUTPUT=""
CONFIG_TYPE="simple"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Logging functions
log_info() {
    echo -e "${GREEN}[INFO]${NC} $*"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $*" >&2
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $*" >&2
}

log_debug() {
    if [[ "${VERBOSE}" == "true" ]]; then
        echo -e "${BLUE}[DEBUG]${NC} $*"
    fi
}

# Execute command with logging and dry-run support
execute_cmd() {
    local cmd="$*"
    log_debug "Executing: $cmd"
    
    if [[ "${DRY_RUN}" == "true" ]]; then
        echo "[DRY-RUN] $cmd"
        return 0
    fi
    
    if [[ "${VERBOSE}" == "true" ]]; then
        eval "$cmd"
    else
        eval "$cmd" >/dev/null 2>&1
    fi
}

# Validation functions  
validate_parameters() {
    # Validate prefix for security (no path traversal)
    if [[ "$PREFIX" =~ \.\.|/ ]]; then
        log_error "Invalid prefix: $PREFIX (cannot contain '..' or '/')"
        exit 1
    fi
    
    # Validate prefix characters (alphanumeric and basic symbols only)
    if ! [[ "$PREFIX" =~ ^[a-zA-Z0-9_-]+$ ]]; then
        log_error "Invalid prefix: $PREFIX (only alphanumeric, underscore, and hyphen allowed)"
        exit 1
    fi
    
    # Validate number of nodes if specified
    if [[ -n "$NODES" ]] && (! [[ "$NODES" =~ ^[0-9]+$ ]] || [[ "$NODES" -lt 1 ]]); then
        log_error "Invalid number of nodes: $NODES"
        exit 1
    fi
}

# Load configuration from file
load_config_file() {
    local config_file="$1"
    
    if [[ ! -f "$config_file" ]]; then
        return 0
    fi
    
    log_debug "Loading configuration from: $config_file"
    
    # Source the config file in a safe way
    while IFS='=' read -r key value; do
        # Skip comments and empty lines
        [[ $key =~ ^[[:space:]]*# ]] && continue
        [[ -z "$key" ]] && continue
        
        # Remove whitespace
        key=$(echo "$key" | xargs)
        value=$(echo "$value" | xargs)
        
        # Set variables based on config keys
        case "$key" in
            nodes) NODES="$value" ;;
            prefix) PREFIX="$value" ;;
            work_dir) WORK_DIR="$value" ;;
            cluster_name) CLUSTER_NAME="$value" ;;
            network_prefix) NETWORK_PREFIX="$value" ;;
            bridge_name) BRIDGE_NAME="$value" ;;
            ssl_enabled) SSL_ENABLED="$value" ;;
            ssl_cert_dir) SSL_CERT_DIR="$value" ;;
            ncs_flags) NCS_FLAGS="$value" ;;
            timeout) TIMEOUT="$value" ;;
            host) HOST="$value" ;;
            env_sh_path) ENV_SH_PATH="$value" ;;
        esac
    done < "$config_file"
}

# Save configuration to file
save_config_file() {
    local config_file="$1"
    
    log_debug "Saving configuration to: $config_file"
    
    cat > "$config_file" << EOF
# RAFT Cluster Configuration
# Generated by $SCRIPT_NAME v$SCRIPT_VERSION

# Cluster settings
nodes=$NODES
cluster_name=$CLUSTER_NAME
prefix=$PREFIX
work_dir=$WORK_DIR

# Network settings
network_prefix=$NETWORK_PREFIX
bridge_name=$BRIDGE_NAME

# NSO settings
ssl_enabled=$SSL_ENABLED
ssl_cert_dir=$SSL_CERT_DIR
ncs_flags=$NCS_FLAGS
host=$HOST
env_sh_path=$ENV_SH_PATH

# Timeouts
timeout=$TIMEOUT
EOF
}

# Find env.sh script
find_env_sh() {
    local search_paths=(
        "$WORK_DIR/env.sh"
        "$(pwd)/env.sh"
        "../env.sh"
        "../../env.sh"
        "../../../env.sh"
    )
    
    # If NCS_DIR is set, try to find env.sh relative to it
    if [[ -n "${NCS_DIR:-}" ]]; then
        search_paths+=("$NCS_DIR/../env.sh")
        search_paths+=("$NCS_DIR/../../env.sh")
        search_paths+=("$NCS_DIR/../../../env.sh")
    fi
    
    for path in "${search_paths[@]}"; do
        if [[ -f "$path" ]] && [[ -r "$path" ]]; then
            echo "$(cd "$(dirname "$path")" && pwd)/$(basename "$path")"
            return 0
        fi
    done
    
    return 1
}

# Prompt for env.sh path
prompt_for_env_sh() {
    echo
    log_warn "NSO environment script (env.sh) not found or not configured"
    
    # Try to find it automatically
    local found_env_sh
    if found_env_sh=$(find_env_sh); then
        log_info "Found env.sh at: $found_env_sh"
        echo -n "Use this path? [Y/n]: "
        read -r response
        if [[ -z "$response" ]] || [[ "$response" =~ ^[Yy] ]]; then
            ENV_SH_PATH="$found_env_sh"
            return 0
        fi
    fi
    
    # Manual input
    while true; do
        echo -n "Please enter the path to env.sh (or 'skip' to continue without): "
        read -r env_path
        
        if [[ "$env_path" == "skip" ]]; then
            log_warn "Continuing without env.sh - NSO commands may not work"
            return 1
        fi
        
        if [[ -f "$env_path" ]] && [[ -r "$env_path" ]]; then
            ENV_SH_PATH="$(cd "$(dirname "$env_path")" && pwd)/$(basename "$env_path")"
            break
        else
            log_error "File not found or not readable: $env_path"
        fi
    done
    
    return 0
}

# Setup NSO environment
setup_nso_environment() {
    # Check if env.sh path is configured
    if [[ -z "$ENV_SH_PATH" ]]; then
        if ! prompt_for_env_sh; then
            return 1
        fi
        
        # Save the path to config file
        if [[ -n "$CONFIG_FILE" ]]; then
            save_config_file "$CONFIG_FILE"
            log_info "Saved env.sh path to configuration file"
        fi
    fi
    
    # Verify the env.sh file exists
    if [[ -n "$ENV_SH_PATH" ]] && [[ ! -f "$ENV_SH_PATH" ]]; then
        log_error "env.sh file not found: $ENV_SH_PATH"
        return 1
    fi
    
    return 0
}

# Get NSO environment sourcing command
get_nso_env_source() {
    if [[ -n "$ENV_SH_PATH" ]]; then
        echo ". '$ENV_SH_PATH'"
    else
        echo ""
    fi
}

# Check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Check prerequisites
check_prerequisites() {
    log_info "Checking prerequisites..."
    
    # Check if running with sufficient privileges
    if [[ $EUID -ne 0 ]] && ! sudo -n true 2>/dev/null; then
        log_error "This script requires root privileges or passwordless sudo access"
        log_error "Add to /etc/sudoers: %sudo ALL=(ALL) NOPASSWD: /usr/sbin/ip,/usr/sbin/iptables"
        exit 1
    fi
    
    # Setup NSO environment if needed
    if [[ "$NO_NSO" != "true" ]]; then
        if ! setup_nso_environment; then
            log_error "Failed to setup NSO environment"
            exit 1
        fi
        
        # Source env.sh to check NSO commands
        local env_source=$(get_nso_env_source)
        if [[ -n "$env_source" ]]; then
            log_debug "Sourcing NSO environment: $ENV_SH_PATH"
            # Test if we can source the environment
            if ! bash -c "$env_source" >/dev/null 2>&1; then
                log_error "Failed to source NSO environment: $ENV_SH_PATH"
                exit 1
            fi
        fi
        
        # Check required NSO commands (after sourcing environment)
        local nso_commands=("ncs-setup" "ncs" "ncs_cmd")
        for cmd in "${nso_commands[@]}"; do
            if ! bash -c "$env_source; command -v $cmd" >/dev/null 2>&1; then
                log_error "Required NSO command not found: $cmd"
                if [[ -z "$env_source" ]]; then
                    log_error "Consider setting up env.sh path for NSO environment"
                fi
                exit 1
            fi
        done
    fi
    
    # Check system commands
    local required_commands=("ip" "iptables")
    for cmd in "${required_commands[@]}"; do
        if ! command_exists "$cmd"; then
            log_error "Required command not found: $cmd"
            exit 1
        fi
    done
    
    # Check NSO environment (only if env.sh is available)
    if [[ "$NO_NSO" != "true" ]] && [[ -n "$ENV_SH_PATH" ]]; then
        local env_source=$(get_nso_env_source)
        local ncs_dir=$(bash -c "$env_source; echo \${NCS_DIR:-}")
        
        if [[ -z "$ncs_dir" ]]; then
            log_error "NCS_DIR environment variable not set after sourcing $ENV_SH_PATH"
            exit 1
        fi
        
        if [[ ! -d "$ncs_dir" ]]; then
            log_error "NCS_DIR directory does not exist: $ncs_dir"
            exit 1
        fi
    fi
    
    log_info "Prerequisites check passed"
}

# Fix Docker's iptables mess
fix_dockers_mess() {
    log_info "Fixing Docker iptables policy..."
    execute_cmd "sudo iptables --policy FORWARD ACCEPT"
}

# Create virtual ethernet pairs
create_veth_pairs() {
    log_info "Creating virtual ethernet pairs..."
    
    for ((i=1; i<=NODES; i++)); do
        local veth_a="${PREFIX}${i}a"
        local veth_b="${PREFIX}${i}b"
        
        log_debug "Creating veth pair: $veth_a <-> $veth_b"
        execute_cmd "sudo ip link add dev $veth_a type veth peer name $veth_b"
    done
}

# Delete virtual ethernet pairs
delete_veth_pairs() {
    log_info "Deleting virtual ethernet pairs..."
    
    for ((i=1; i<=NODES; i++)); do
        local veth_b="${PREFIX}${i}b"
        
        if ip link show "$veth_b" >/dev/null 2>&1; then
            log_debug "Deleting veth pair: $veth_b"
            execute_cmd "sudo ip link del dev $veth_b"
        fi
    done
}

# Create hosts file for a namespace
create_hosts_file() {
    local node_id="$1"
    local hosts_dir="${WORK_DIR}/hosts/${PREFIX}${node_id}ns"
    local hosts_file="${hosts_dir}/hosts"
    
    log_debug "Creating hosts file for node $node_id"
    
    execute_cmd "mkdir -p $hosts_dir"
    
    if [[ "${DRY_RUN}" == "true" ]]; then
        log_debug "[DRY-RUN] Would create hosts file: $hosts_file"
        return 0
    fi
    
    cat > "$hosts_file" << EOF
127.0.0.1   localhost
::1         localhost ip6-localhost ip6-loopback
fe00::0     ip6-localnet
ff00::0     ip6-mcastprefix
ff02::1     ip6-allnodes
ff02::2     ip6-allrouters

# HA Cluster nodes
EOF

    # Add entries for all cluster nodes
    for ((j=1; j<=NODES; j++)); do
        echo "${NETWORK_PREFIX}.${j}.1    ${PREFIX}${j}.ha-cluster" >> "$hosts_file"
    done
}

# Create all hosts files
create_hosts_files() {
    log_info "Creating hosts files..."
    
    for ((i=1; i<=NODES; i++)); do
        create_hosts_file "$i"
    done
}

# Add hosts file to namespace
add_hosts_to_namespace() {
    local node_id="$1"
    local netns_dir="/etc/netns/${PREFIX}${node_id}ns"
    local hosts_src="${WORK_DIR}/hosts/${PREFIX}${node_id}ns/hosts"
    
    log_debug "Adding hosts file to namespace ${PREFIX}${node_id}ns"
    
    execute_cmd "sudo mkdir -p $netns_dir"
    execute_cmd "sudo cp $hosts_src $netns_dir/hosts"
}

# Remove hosts file from namespace
remove_hosts_from_namespace() {
    local node_id="$1"
    local netns_dir="/etc/netns/${PREFIX}${node_id}ns"
    
    if [[ -f "$netns_dir/hosts" ]]; then
        log_debug "Removing hosts file from namespace ${PREFIX}${node_id}ns"
        execute_cmd "sudo rm $netns_dir/hosts"
        execute_cmd "sudo rmdir $netns_dir" || true
    fi
}

# Create network namespaces
create_namespaces() {
    log_info "Creating network namespaces..."
    
    for ((i=1; i<=NODES; i++)); do
        local netns="${PREFIX}${i}ns"
        local veth_a="${PREFIX}${i}a"
        local node_ip="${NETWORK_PREFIX}.${i}.1"
        
        log_debug "Creating namespace: $netns"
        
        # Create namespace
        execute_cmd "sudo ip netns add $netns"
        
        # Move veth interface to namespace
        execute_cmd "sudo ip link set dev $veth_a netns $netns"
        
        # Configure interface in namespace
        execute_cmd "sudo ip -n $netns addr add ${node_ip}/16 dev $veth_a"
        execute_cmd "sudo ip -n $netns link set dev $veth_a up"
        execute_cmd "sudo ip -n $netns link set dev lo up"
        
        # Add default route
        execute_cmd "sudo ip -n $netns route add default via ${node_ip} dev $veth_a"
        
        # Add hosts file
        add_hosts_to_namespace "$i"
    done
}

# Delete network namespaces
delete_namespaces() {
    log_info "Deleting network namespaces..."
    
    for ((i=1; i<=NODES; i++)); do
        local netns="${PREFIX}${i}ns"
        local veth_a="${PREFIX}${i}a"
        
        if ip netns list | grep -q "^$netns"; then
            log_debug "Deleting namespace: $netns"
            
            # Move interface back to root namespace (if it exists)
            if sudo ip -n "$netns" link show "$veth_a" >/dev/null 2>&1; then
                execute_cmd "sudo ip -n $netns link set dev $veth_a netns 1" || true
            fi
            
            # Delete namespace
            execute_cmd "sudo ip netns del $netns"
            
            # Remove hosts file
            remove_hosts_from_namespace "$i"
        fi
    done
}

# Setup bridge network
setup_bridge() {
    log_info "Setting up bridge network..."
    
    # Create bridge
    execute_cmd "sudo ip link add dev $BRIDGE_NAME type bridge"
    
    # Connect all veth interfaces to bridge
    for ((i=1; i<=NODES; i++)); do
        local veth_b="${PREFIX}${i}b"
        
        log_debug "Connecting $veth_b to bridge $BRIDGE_NAME"
        execute_cmd "sudo ip link set dev $veth_b master $BRIDGE_NAME"
        execute_cmd "sudo ip link set dev $veth_b up"
    done
    
    # Add gateway address to bridge
    execute_cmd "sudo ip addr add ${NETWORK_PREFIX}.0.254/16 dev $BRIDGE_NAME"
    execute_cmd "sudo ip link set dev $BRIDGE_NAME up"
}

# Cleanup bridge network
cleanup_bridge() {
    log_info "Cleaning up bridge network..."
    
    if ip link show "$BRIDGE_NAME" >/dev/null 2>&1; then
        # Disconnect interfaces from bridge
        for ((i=1; i<=NODES; i++)); do
            local veth_b="${PREFIX}${i}b"
            
            if ip link show "$veth_b" >/dev/null 2>&1; then
                log_debug "Disconnecting $veth_b from bridge"
                execute_cmd "sudo ip link set $veth_b nomaster" || true
                execute_cmd "sudo ip link set $veth_b down" || true
            fi
        done
        
        # Delete bridge
        execute_cmd "sudo ip link set dev $BRIDGE_NAME down"
        execute_cmd "sudo ip link del $BRIDGE_NAME"
    fi
}

# Validate network connectivity
validate_network() {
    log_info "Validating network connectivity..."
    
    if [[ "${DRY_RUN}" == "true" ]]; then
        log_debug "[DRY-RUN] Skipping network validation"
        return 0
    fi
    
    # Check bridge interface
    if ! ip addr show "$BRIDGE_NAME" | grep -q "UP,LOWER_UP"; then
        log_error "Bridge interface $BRIDGE_NAME is not up"
        return 1
    fi
    
    if ! ip addr show "$BRIDGE_NAME" | grep -q "inet ${NETWORK_PREFIX}.0.254/16"; then
        log_error "Bridge interface missing gateway address"
        return 1
    fi
    
    # Check namespace interfaces
    for ((i=1; i<=NODES; i++)); do
        local netns="${PREFIX}${i}ns"
        local veth_a="${PREFIX}${i}a"
        local veth_b="${PREFIX}${i}b"
        local node_ip="${NETWORK_PREFIX}.${i}.1"
        
        # Check veth pair is up
        if ! ip link show "$veth_b" | grep -q "UP,LOWER_UP"; then
            log_error "Interface $veth_b is not up"
            return 1
        fi
        
        # Check namespace interface
        if ! sudo ip -n "$netns" addr show "$veth_a" | grep -q "UP,LOWER_UP"; then
            log_error "Namespace interface $veth_a in $netns is not up"
            return 1
        fi
        
        if ! sudo ip -n "$netns" addr show "$veth_a" | grep -q "inet ${node_ip}/16"; then
            log_error "Namespace interface missing IP address: $node_ip"
            return 1
        fi
    done
    
    log_info "Network validation passed"
}

# Test network connectivity between nodes
test_connectivity() {
    log_info "Testing network connectivity..."
    
    if [[ "${DRY_RUN}" == "true" ]]; then
        log_debug "[DRY-RUN] Skipping connectivity tests"
        return 0
    fi
    
    for ((i=1; i<=NODES; i++)); do
        local netns="${PREFIX}${i}ns"
        
        # Test ping to next node (circular)
        local next_node=$((i % NODES + 1))
        local target_ip="${NETWORK_PREFIX}.${next_node}.1"
        
        log_debug "Testing ping from node $i to node $next_node"
        
        if ! execute_cmd "sudo ip netns exec $netns ping -c 1 -W 2 $target_ip"; then
            log_error "Ping failed from node $i to node $next_node"
            return 1
        fi
        
        # Test hostname resolution
        local target_hostname="${PREFIX}${next_node}.ha-cluster"
        if ! execute_cmd "sudo ip netns exec $netns ping -c 1 -W 2 $target_hostname"; then
            log_error "Hostname resolution failed from node $i to $target_hostname"
            return 1
        fi
    done
    
    log_info "Connectivity test passed"
}

# Isolate a single node from the cluster (simulate cable disconnect)
isolate_node() {
    local node_id="$1"
    local netns="${PREFIX}${node_id}ns"
    local veth_b="${PREFIX}${node_id}b"
    
    if ! ip netns list | grep -q "^$netns"; then
        log_error "Namespace $netns does not exist"
        return 1
    fi
    
    if ! ip link show "$veth_b" >/dev/null 2>&1; then
        log_error "Interface $veth_b does not exist"
        return 1
    fi
    
    log_info "Isolating node $node_id from cluster (simulating cable disconnect)"
    
    # Method 1: Bring down the bridge-side interface
    log_debug "Bringing down interface $veth_b"
    execute_cmd "sudo ip link set $veth_b down"
    
    # Method 2: Remove from bridge (but keep interface up for later healing)
    log_debug "Removing $veth_b from bridge $BRIDGE_NAME"
    execute_cmd "sudo ip link set $veth_b nomaster"
    
    log_info "Node $node_id is now isolated from the cluster"
    log_info "Use 'heal $node_id' or 'heal' to restore connectivity"
}

# Create a network partition between groups of nodes
create_partition() {
    local partition_spec="$1"
    
    if [[ ! "$partition_spec" =~ ^[0-9,]+$ ]]; then
        log_error "Invalid partition specification. Use format like '1,2' to isolate nodes 1 and 2"
        return 1
    fi
    
    # Parse the partition specification
    IFS=',' read -ra partition_nodes <<< "$partition_spec"
    
    # Validate node IDs
    for node_id in "${partition_nodes[@]}"; do
        if [[ ! "$node_id" =~ ^[0-9]+$ ]] || [[ "$node_id" -lt 1 ]] || [[ "$node_id" -gt "$NODES" ]]; then
            log_error "Invalid node ID: $node_id (must be between 1 and $NODES)"
            return 1
        fi
    done
    
    log_info "Creating network partition: nodes [${partition_spec}] vs remaining nodes"
    
    # Create a temporary bridge for the partitioned nodes
    local partition_bridge="${BRIDGE_NAME}part"
    log_debug "Creating partition bridge: $partition_bridge"
    execute_cmd "sudo ip link add dev $partition_bridge type bridge"
    execute_cmd "sudo ip addr add ${NETWORK_PREFIX}.99.254/16 dev $partition_bridge"
    execute_cmd "sudo ip link set dev $partition_bridge up"
    
    # Move specified nodes to the partition bridge
    for node_id in "${partition_nodes[@]}"; do
        local veth_b="${PREFIX}${node_id}b"
        local netns="${PREFIX}${node_id}ns"
        
        if ! ip netns list | grep -q "^$netns"; then
            log_warn "Namespace $netns does not exist, skipping node $node_id"
            continue
        fi
        
        if ! ip link show "$veth_b" >/dev/null 2>&1; then
            log_warn "Interface $veth_b does not exist, skipping node $node_id"
            continue
        fi
        
        log_debug "Moving node $node_id to partition bridge"
        execute_cmd "sudo ip link set $veth_b nomaster"
        execute_cmd "sudo ip link set $veth_b master $partition_bridge"
        execute_cmd "sudo ip link set $veth_b up"
    done
    
    log_info "Network partition created successfully"
    log_info "Partitioned nodes: [${partition_spec}]"
    log_info "Main cluster nodes: [$(get_remaining_nodes "$partition_spec")]"
    log_info "Use 'heal' to restore full connectivity"
}

# Get list of nodes not in the partition
get_remaining_nodes() {
    local partition_spec="$1"
    IFS=',' read -ra partition_nodes <<< "$partition_spec"
    
    local remaining=()
    for ((i=1; i<=NODES; i++)); do
        local is_partitioned=false
        for partitioned_node in "${partition_nodes[@]}"; do
            if [[ "$i" == "$partitioned_node" ]]; then
                is_partitioned=true
                break
            fi
        done
        if [[ "$is_partitioned" == "false" ]]; then
            remaining+=("$i")
        fi
    done
    
    # Join array with commas
    local IFS=','
    echo "${remaining[*]}"
}

# Heal network partition (restore connectivity)
heal_partition() {
    local specific_node="$1"
    
    if [[ -n "$specific_node" ]]; then
        log_info "Healing connectivity for node $specific_node"
        heal_single_node "$specific_node"
    else
        log_info "Healing all network partitions"
        heal_all_nodes
    fi
}

# Heal a specific node
heal_single_node() {
    local node_id="$1"
    local netns="${PREFIX}${node_id}ns"
    local veth_b="${PREFIX}${node_id}b"
    
    if ! ip netns list | grep -q "^$netns"; then
        log_error "Namespace $netns does not exist"
        return 1
    fi
    
    if ! ip link show "$veth_b" >/dev/null 2>&1; then
        log_error "Interface $veth_b does not exist"
        return 1
    fi
    
    log_debug "Restoring connectivity for node $node_id"
    
    # Remove from any partition bridge
    execute_cmd "sudo ip link set $veth_b nomaster" 2>/dev/null || true
    
    # Add back to main bridge
    execute_cmd "sudo ip link set $veth_b master $BRIDGE_NAME"
    execute_cmd "sudo ip link set $veth_b up"
    
    log_info "Node $node_id connectivity restored"
}

# Heal all nodes and remove partition bridges
heal_all_nodes() {
    # First, restore all nodes to main bridge
    for ((i=1; i<=NODES; i++)); do
        local veth_b="${PREFIX}${i}b"
        if ip link show "$veth_b" >/dev/null 2>&1; then
            log_debug "Restoring node $i to main bridge"
            execute_cmd "sudo ip link set $veth_b nomaster" 2>/dev/null || true
            execute_cmd "sudo ip link set $veth_b master $BRIDGE_NAME"
            execute_cmd "sudo ip link set $veth_b up"
        fi
    done
    
    # Remove any partition bridges
    local partition_bridge="${BRIDGE_NAME}part"
    if ip link show "$partition_bridge" >/dev/null 2>&1; then
        log_debug "Removing partition bridge: $partition_bridge"
        execute_cmd "sudo ip link set dev $partition_bridge down"
        execute_cmd "sudo ip link del $partition_bridge"
    fi
    
    log_info "All network partitions healed - full connectivity restored"
}

# Test connectivity and show partition status
show_partition_status() {
    log_info "Network Partition Status:"
    echo ""
    
    # Show bridge status
    echo "  Bridges:"
    if ip link show "$BRIDGE_NAME" >/dev/null 2>&1; then
        local main_members=$(bridge link show | grep "$BRIDGE_NAME" | wc -l)
        echo "    Main bridge ($BRIDGE_NAME): $main_members members"
        bridge link show | grep "$BRIDGE_NAME" | while read -r line; do
            echo "      $line"
        done
    fi
    
    local partition_bridge="${BRIDGE_NAME}part"
    if ip link show "$partition_bridge" >/dev/null 2>&1; then
        local partition_members=$(bridge link show | grep "$partition_bridge" | wc -l)
        echo "    Partition bridge ($partition_bridge): $partition_members members"
        bridge link show | grep "$partition_bridge" | while read -r line; do
            echo "      $line"
        done
    fi
    
    echo ""
    echo "  Node Connectivity Matrix:"
    echo -n "    From\\To: "
    for ((j=1; j<=NODES; j++)); do
        printf "%8s" "Node$j"
    done
    echo ""
    
    # Test connectivity between all pairs
    for ((i=1; i<=NODES; i++)); do
        local netns_i="${PREFIX}${i}ns"
        printf "%12s" "Node$i:"
        
        for ((j=1; j<=NODES; j++)); do
            if [[ "$i" == "$j" ]]; then
                printf "%8s" "SELF"
            else
                local target_ip="${NETWORK_PREFIX}.${j}.1"
                if sudo ip netns exec "$netns_i" ping -c 1 -W 1 "$target_ip" >/dev/null 2>&1; then
                    printf "%8s" "✓"
                else
                    printf "%8s" "✗"
                fi
            fi
        done
        echo ""
    done
}

# Get seed node address for a given node
get_seed_node_address() {
    local node_id="$1"
    local seed_id=$((node_id % NODES + 1))
    echo "ncsd${seed_id}@${PREFIX}${seed_id}.ha-cluster"
}

# Setup NSO node directory and configuration
setup_nso_node() {
    local node_id="$1"
    local node_dir="${WORK_DIR}/ncs-run${node_id}"
    local node_ip="${NETWORK_PREFIX}.${node_id}.1"
    local node_address="ncsd${node_id}@${PREFIX}${node_id}.ha-cluster"
    local seed_address=$(get_seed_node_address "$node_id")
    local env_source=$(get_nso_env_source)
    
    log_debug "Setting up NSO node $node_id in $node_dir"
    
    # Remove existing directory if it exists
    if [[ -d "$node_dir" ]]; then
        log_debug "Removing existing directory: $node_dir"
        execute_cmd "rm -rf $node_dir"
    fi
    
    # Ensure parent directory exists
    local parent_dir=$(dirname "$node_dir")
    if [[ ! -d "$parent_dir" ]]; then
        log_debug "Creating parent directory: $parent_dir"
        execute_cmd "mkdir -p $parent_dir"
    fi
    
    # Create NSO runtime directory (with environment sourced)
    log_debug "Running ncs-setup for node $node_id"
    if [[ "${DRY_RUN}" == "true" ]]; then
        echo "[DRY-RUN] bash -c '$env_source; ncs-setup --dest $node_dir --no-netsim'"
    else
        if ! bash -c "$env_source; ncs-setup --dest $node_dir --no-netsim"; then
            log_error "Failed to run ncs-setup for node $node_id"
            return 1
        fi
    fi
    
    # Verify the directory was created
    if [[ ! -d "$node_dir" ]] && [[ "${DRY_RUN}" != "true" ]]; then
        log_error "NSO directory was not created: $node_dir"
        return 1
    fi
    
    # Apply basic configuration modifications
    apply_basic_nso_config "$node_id" "$node_dir" "$node_ip"
    
    # Apply RAFT configuration
    apply_raft_config "$node_id" "$node_dir" "$node_address" "$seed_address"
    
    # Apply SSL configuration if enabled
    if [[ "$SSL_ENABLED" == "true" ]]; then
        apply_ssl_config "$node_id" "$node_dir"
    fi
}

# Apply basic NSO configuration changes
apply_basic_nso_config() {
    local node_id="$1"
    local node_dir="$2"
    local node_ip="$3"
    local ncs_conf="$node_dir/ncs.conf"
    
    log_debug "Applying basic NSO configuration for node $node_id"
    
    # Backup original config
    execute_cmd "cp $ncs_conf ${ncs_conf}.bk"
    
    # Apply sed transformations for basic config  
    execute_cmd "sed -i \\
        -e '/<webui>/,/<\\/webui>/ s|<enabled>true</enabled>|<enabled>false</enabled>|' \\
        -e 's/0\\.0\\.0\\.0/${node_ip}/g' \\
        -e 's|<cli>|<cli><default-table-behavior>dynamic</default-table-behavior>|g' \\
        -e 's|</ncs-config>|<ncs-ipc-address><ip>${node_ip}</ip></ncs-ipc-address>\\n&|' \\
        \"$ncs_conf\""
}

# Apply RAFT cluster configuration
apply_raft_config() {
    local node_id="$1"
    local node_dir="$2"
    local node_address="$3"
    local seed_address="$4"
    local ncs_conf="$node_dir/ncs.conf"
    local ssl_keyfile="../erldist/ssl/ncs${node_id}/server_key.pem"
    local ssl_certfile="../erldist/ssl/ca/certs/${PREFIX}${node_id}_cert.pem"
    local ssl_cacertfile="../erldist/ssl/ca/cert.pem"
    local ssl_crldir="../erldist/ssl/crl"
    
    log_debug "Applying RAFT configuration for node $node_id"
    
    # Apply RAFT configuration via sed
    execute_cmd "sed -i '/<ha-raft>/,/<\\/ha-raft>/{
        s/<!-- \\(.*\\) -->/\\1/;
        s|<\\(cluster-name\\)>[^<]*</\\1>|<\\1>${CLUSTER_NAME}</\\1>|;
        s|<\\(node-address\\)>[^<]*</\\1>|<\\1>${node_address}</\\1>|;
        s|<\\(seed-node\\)>n2\\.[^<]*</\\1>|<\\1>${seed_address}</\\1>|;
        s|<\\(key-file\\)>[^<]*</\\1>|<\\1>${ssl_keyfile}</\\1>|;
        s|<\\(cert-file\\)>[^<]*</\\1>|<\\1>${ssl_certfile}</\\1>|;
        s|<\\(ca-cert-file\\)>[^<]*</\\1>|<\\1>${ssl_cacertfile}</\\1>|;
        s|</ca-cert-file>|&<crl-dir>${ssl_crldir}</crl-dir>|;
    }' \"$ncs_conf\""
    
    # Create TCP version (SSL disabled)
    execute_cmd "sed '/<ha-raft>/,/<\\/ha-raft>/{
        /<ssl>/,/<enabled>/s/>true</>false</;
    }' \"$ncs_conf\" >\"${ncs_conf}.tcp\""
    
    # Create IP version (using IP addresses instead of hostnames)
    execute_cmd "sed '/<ha-raft>/,/<\\/ha-raft>/{
        s/@[^<]*/@127.0.0.1/g;
    }' \"$ncs_conf\" >\"${ncs_conf}.ip\""
}

# Apply SSL configuration for WebUI and Erlang distribution
apply_ssl_config() {
    local node_id="$1"
    local node_dir="$2"
    local ncs_conf="$node_dir/ncs.conf"
    local ssl_keyfile="../erldist/ssl/ncs${node_id}/server_key.pem"
    local ssl_certfile="../erldist/ssl/ca/certs/${PREFIX}${node_id}_cert.pem"
    local ssl_cacertfile="../erldist/ssl/ca/cert.pem"
    
    log_debug "Applying SSL configuration for node $node_id"
    
    # Configure WebUI SSL
    execute_cmd "sed -i '/<webui>/,/<\\/webui>/{
        s/<!-- \\(.*\\) -->/\\1/;
        s|<\\(key-file\\)>[^<]*</\\1>|<\\1>${ssl_keyfile}</\\1>|;
        s|<\\(cert-file\\)>[^<]*</\\1>|<\\1>${ssl_certfile}</\\1>|;
        s|</cert-file>|&<ca-cert-file>${ssl_cacertfile}</ca-cert-file>|;
    }' \"$ncs_conf\""
    
    # Enable SSL in RAFT configuration
    execute_cmd "sed -i '/<ha-raft>/,/<\\/ha-raft>/{
        s|<ssl>.*|<ssl><enabled>true</enabled>|;
    }' \"$ncs_conf\""
}

# Setup all NSO nodes
setup_nso_nodes() {
    if [[ "$NO_NSO" == "true" ]]; then
        log_info "Skipping NSO setup (--no-nso flag set)"
        return
    fi
    
    log_info "Setting up NSO nodes..."
    
    for ((i=1; i<=NODES; i++)); do
        setup_nso_node "$i"
    done
    
    log_info "NSO nodes setup completed"
}

# Start a single NSO node
start_nso_node() {
    local node_id="$1"
    local node_dir="${WORK_DIR}/ncs-run${node_id}"
    local netns="${PREFIX}${node_id}ns"
    local node_ip="${NETWORK_PREFIX}.${node_id}.1"
    local env_source=$(get_nso_env_source)
    
    if [[ ! -d "$node_dir" ]]; then
        log_error "NSO node directory does not exist: $node_dir"
        return 1
    fi
    
    log_debug "Starting NSO node $node_id in namespace $netns"
    
    # Start NCS in the namespace (with environment sourced)
    execute_cmd "sudo ip netns exec $netns bash -c '
        $env_source
        export NCS_IPC_ADDR=$node_ip
        export NCS_DEBUG_DUMP_NAME=\"\${LUX_EXTRA_LOGS:-/tmp}/$node_dir/stop.dump\"
        cd $node_dir
        ncs $NCS_FLAGS
    '"
}

# Start NSO nodes
start_nso_nodes() {
    if [[ "$NO_NSO" == "true" ]]; then
        log_info "Skipping NSO start (--no-nso flag set)"
        return
    fi
    
    log_info "Starting NSO nodes..."
    
    if [[ -n "$SPECIFIC_NODE" ]]; then
        # Start specific node
        start_nso_node "$SPECIFIC_NODE"
        log_info "Started NSO node $SPECIFIC_NODE"
    else
        # Start all nodes
        for ((i=1; i<=NODES; i++)); do
            start_nso_node "$i"
        done
        log_info "All NSO nodes started"
    fi
}

# Stop a single NSO node
stop_nso_node() {
    local node_id="$1"
    local node_ip="${NETWORK_PREFIX}.${node_id}.1"
    local netns="${PREFIX}${node_id}ns"
    local env_source=$(get_nso_env_source)
    
    log_debug "Stopping NSO node $node_id"
    
    # Try to stop gracefully first (with environment sourced)
    execute_cmd "sudo ip netns exec $netns bash -c '
        $env_source
        export NCS_IPC_ADDR=$node_ip
        ncs --stop
    '" || true
    
    # Wait a moment for graceful shutdown
    sleep 2
    
    # Force kill if still running
    local pids=$(sudo ip netns exec "$netns" pgrep -f "beam.*ncs" 2>/dev/null || true)
    if [[ -n "$pids" ]]; then
        log_debug "Force killing NSO processes for node $node_id: $pids"
        echo "$pids" | xargs -r sudo ip netns exec "$netns" kill -9 || true
    fi
}

# Stop NSO nodes
stop_nso_nodes() {
    log_info "Stopping NSO nodes..."
    
    local stop_failed=false
    
    if [[ -n "$SPECIFIC_NODE" ]]; then
        if ! stop_nso_node "$SPECIFIC_NODE"; then
            log_warn "Failed to stop NSO node $SPECIFIC_NODE"
            stop_failed=true
        else
            log_info "Stopped NSO node $SPECIFIC_NODE"
        fi
    else
        for ((i=1; i<=NODES; i++)); do
            if ! stop_nso_node "$i"; then
                log_warn "Failed to stop NSO node $i"
                stop_failed=true
            fi
        done
        
        if [[ "$stop_failed" == "true" ]]; then
            log_warn "Some NSO nodes failed to stop cleanly"
        else
            log_info "All NSO nodes stopped"
        fi
    fi
    
    return 0  # Always return success to allow cleanup to continue
}

# Cleanup NSO configuration directories
cleanup_nso_nodes() {
    if [[ "$KEEP_CONFIG" == "true" ]]; then
        log_info "Keeping NSO configuration directories"
        return 0
    fi
    
    log_info "Cleaning up NSO configuration directories..."
    
    local cleanup_failed=false
    
    for ((i=1; i<=NODES; i++)); do
        local node_dir="${WORK_DIR}/ncs-run${i}"
        if [[ -d "$node_dir" ]]; then
            if ! execute_cmd "rm -rf $node_dir"; then
                log_warn "Failed to remove NSO directory: $node_dir"
                cleanup_failed=true
            fi
        fi
    done
    
    if [[ "$cleanup_failed" == "true" ]]; then
        log_warn "Some NSO directories could not be removed"
        return 1
    fi
    
    return 0
}

# Check NSO node status
check_nso_node_status() {
    local node_id="$1"
    local node_ip="${NETWORK_PREFIX}.${node_id}.1"
    local netns="${PREFIX}${node_id}ns"
    local env_source=$(get_nso_env_source)
    
    # Check if NSO process is running
    local pids=$(sudo ip netns exec "$netns" pgrep -f "beam.*ncs" 2>/dev/null || true)
    if [[ -z "$pids" ]]; then
        echo "STOPPED"
        return
    fi
    
    # Try to get RAFT role
    local role=$(sudo ip netns exec "$netns" bash -c "
        $env_source
        export NCS_IPC_ADDR=$node_ip
        timeout 5 ncs_cmd -I -c 'mget /ha-raft/status/role' 2>/dev/null || echo 'unknown'
    ")
    
    echo "RUNNING ($role)"
}

# Show NSO cluster status
show_nso_status() {
    if [[ "$NO_NSO" == "true" ]]; then
        echo "  NSO: DISABLED"
        return
    fi
    
    echo "  NSO Nodes:"
    for ((i=1; i<=NODES; i++)); do
        local node_dir="${WORK_DIR}/ncs-run${i}"
        local status="NOT_CONFIGURED"
        
        if [[ -d "$node_dir" ]]; then
            status=$(check_nso_node_status "$i")
        fi
        
        echo "    Node $i: $status"
    done
    
    # Try to show leader information
    echo ""
    echo "  RAFT Status:"
    local env_source=$(get_nso_env_source)
    for ((i=1; i<=NODES; i++)); do
        local node_ip="${NETWORK_PREFIX}.${i}.1"
        local netns="${PREFIX}${i}ns"
        
        local leader=$(sudo ip netns exec "$netns" bash -c "
            $env_source
            export NCS_IPC_ADDR=$node_ip
            timeout 5 ncs_cmd -I -c 'mget /ha-raft/status/leader' 2>/dev/null || echo 'unknown'
        " 2>/dev/null || echo "unknown")
        
        if [[ "$leader" != "unknown" ]] && [[ "$leader" != "error" ]]; then
            echo "    Leader (from node $i): $leader"
            break
        fi
    done
}

# Setup complete network infrastructure
setup_network() {
    log_info "Setting up virtual network infrastructure..."
    
    check_prerequisites
    fix_dockers_mess
    create_hosts_files
    create_veth_pairs
    create_namespaces
    setup_bridge
    validate_network
    
    if [[ "${DRY_RUN}" != "true" ]]; then
        test_connectivity
    fi
    
    log_info "Network setup completed successfully"
}

# Setup complete environment (network + NSO)
setup_environment() {
    setup_network
    setup_nso_nodes
    log_info "Environment setup completed successfully"
}

# Cleanup network infrastructure
cleanup_network() {
    log_info "Cleaning up virtual network infrastructure..."
    
    cleanup_bridge
    delete_namespaces  
    delete_veth_pairs
    
    # Clean up hosts files
    if [[ -d "${WORK_DIR}/hosts" ]]; then
        execute_cmd "rm -rf ${WORK_DIR}/hosts"
    fi
    
    log_info "Network cleanup completed"
}

# Cleanup complete environment (NSO + network)
cleanup_environment() {
    local cleanup_failed=false
    
    if [[ "$NO_NSO" != "true" ]]; then
        if ! stop_nso_nodes; then
            log_warn "Failed to stop some NSO nodes, continuing with cleanup..."
            cleanup_failed=true
        fi
        
        if ! cleanup_nso_nodes; then
            log_warn "Failed to cleanup some NSO directories, continuing with network cleanup..."
            cleanup_failed=true
        fi
    fi
    
    if ! cleanup_network; then
        log_error "Failed to cleanup network infrastructure"
        cleanup_failed=true
    fi
    
    if [[ "$cleanup_failed" == "true" ]]; then
        log_warn "Cleanup completed with some errors"
    else
        log_info "Environment cleanup completed successfully"
    fi
}

# Show usage information
show_usage() {
    cat << EOF
$SCRIPT_NAME v$SCRIPT_VERSION - RAFT Cluster Virtual Network Setup

USAGE:
    $SCRIPT_NAME <command> [options]

COMMANDS:
    setup                   Setup the complete environment (network + NSO)
    start [node_id]         Start NSO nodes (all or specific node)
    stop [node_id]          Stop NSO nodes (all or specific node)
    cleanup                 Cleanup complete environment
    status                  Show current network and NSO status
    shell <node_id>         Enter namespace shell for debugging
    exec <node_id> <cmd>    Execute command in specific namespace
    test                    Test network connectivity
    isolate <node_id>       Isolate single node (simulate cable disconnect)
    partition <nodes>       Create network partition between groups (e.g., "1,2")
    heal [node_id]          Heal network partition (all nodes or specific node)
    configure               Create/generate configuration files
    help                    Show this help message

GLOBAL OPTIONS:
    -n, --nodes <count>     Number of nodes in cluster (default: $DEFAULT_NODES)
    -p, --prefix <prefix>   Node name prefix (default: $DEFAULT_PREFIX)
    -d, --work-dir <dir>    Working directory (default: current)
    -c, --config <file>     Configuration file (default: $DEFAULT_CONFIG_FILE)
    -v, --verbose           Verbose output
    -h, --help              Show help
    --dry-run               Show commands without executing

SETUP OPTIONS:
    --cluster-name <name>   RAFT cluster name (default: $DEFAULT_CLUSTER_NAME)
    --network-prefix <ip>   Network address prefix (default: $DEFAULT_NETWORK_PREFIX)
    --bridge-name <name>    Bridge interface name (default: $DEFAULT_BRIDGE_NAME)
    --ssl-enabled           Enable SSL for Erlang distribution
    --ssl-cert-dir <dir>    SSL certificate directory
    --ncs-flags <flags>     Additional flags to pass to NCS
    --no-nso                Setup only network, skip NSO configuration

CLEANUP OPTIONS:
    --force                 Force cleanup even if nodes are running
    --keep-config           Keep NSO configuration directories

EXAMPLES:
    # Basic 3-node cluster setup
    $SCRIPT_NAME setup

    # Setup 5-node cluster with SSL enabled
    $SCRIPT_NAME setup -n 5 --ssl-enabled

    # Setup network only (no NSO)
    $SCRIPT_NAME setup --no-nso

    # Use custom configuration file
    $SCRIPT_NAME setup -c my-cluster.conf

    # Start all NSO nodes and wait for leader
    $SCRIPT_NAME start

    # Start specific node
    $SCRIPT_NAME start 2

    # Enter shell for node 2
    $SCRIPT_NAME shell 2

    # Execute NCS command on node 1
    $SCRIPT_NAME exec 1 "ncs_cli -u admin"

    # Test connectivity
    $SCRIPT_NAME test

    # Simulate different failure scenarios
    $SCRIPT_NAME isolate 1              # Node failure: disconnect node 1
    $SCRIPT_NAME partition 1,2          # Network split: create 2-node partition
    $SCRIPT_NAME partition 1            # Equivalent to isolate 1 
    $SCRIPT_NAME heal                   # Heal all partitions
    $SCRIPT_NAME heal 1                 # Heal only node 1

    # Complete cleanup
    $SCRIPT_NAME cleanup --force

    # Generate configuration files
    $SCRIPT_NAME configure --auto                          # Auto-generate simple config
    $SCRIPT_NAME configure --auto --type l3bgp             # Auto-generate L3 BGP config
    $SCRIPT_NAME configure --auto --nodes 5 --output my.conf
    $SCRIPT_NAME configure                                  # Interactive wizard

CONFIGURE OPTIONS:
    --auto                  Auto-generate configuration (no prompts)
    --type <type>           Configuration type: simple, l3bgp (default: simple)
    --output <file>         Output configuration file (default: .raft-cluster.conf)
    --nodes <count>         Number of nodes for auto-generation
    --force                 Overwrite existing configuration file

CONFIGURATION FILE:
    Create a .raft-cluster.conf file to store default settings:
    
    # Cluster settings
    nodes=3
    cluster_name=my-cluster
    prefix=ha
    work_dir=/tmp/raft-test
    env_sh_path=/path/to/env.sh
    
    # Network settings
    network_prefix=192.168
    bridge_name=ha-cluster
    
    # NSO settings  
    ssl_enabled=false
    ncs_flags=-v

EOF
}

# Parse command line arguments
parse_args() {
    if [[ $# -eq 0 ]]; then
        show_usage
        exit 1
    fi
    
    local command="$1"
    shift
    
    # First pass: look for config file option
    local temp_args=("$@")
    for ((i=0; i<${#temp_args[@]}; i++)); do
        if [[ "${temp_args[i]}" == "-c" ]] || [[ "${temp_args[i]}" == "--config" ]]; then
            CONFIG_FILE="${temp_args[i+1]}"
            break
        fi
    done
    
    # Set default config file path if not specified
    if [[ -z "$CONFIG_FILE" ]]; then
        CONFIG_FILE="$DEFAULT_CONFIG_FILE"
    fi
    
    # Load configuration file if it exists
    if [[ -f "$CONFIG_FILE" ]]; then
        load_config_file "$CONFIG_FILE"
    fi
    
    # Second pass: parse all arguments (these will override config file)
    while [[ $# -gt 0 ]]; do
        case $1 in
            -n|--nodes)
                NODES="$2"
                shift 2
                ;;
            -p|--prefix)
                PREFIX="$2"
                shift 2
                ;;
            -d|--work-dir)
                WORK_DIR="$2"
                shift 2
                ;;
            -c|--config)
                # Already handled in first pass
                shift 2
                ;;
            --cluster-name)
                CLUSTER_NAME="$2"
                shift 2
                ;;
            --network-prefix)
                NETWORK_PREFIX="$2"
                shift 2
                ;;
            --bridge-name)
                BRIDGE_NAME="$2"
                shift 2
                ;;
            --ssl-enabled)
                SSL_ENABLED=true
                shift
                ;;
            --ssl-cert-dir)
                SSL_CERT_DIR="$2"
                shift 2
                ;;
            --ncs-flags)
                NCS_FLAGS="$2"
                shift 2
                ;;
            --no-nso)
                NO_NSO=true
                shift
                ;;
            --timeout)
                TIMEOUT="$2"
                shift 2
                ;;
            --keep-config)
                KEEP_CONFIG=true
                shift
                ;;
            -v|--verbose)
                VERBOSE=true
                shift
                ;;
            --dry-run)
                DRY_RUN=true
                shift
                ;;
            --force)
                FORCE=true
                shift
                ;;
            --auto)
                AUTO_GENERATE=true
                shift
                ;;
            --output)
                shift
                CONFIG_OUTPUT="$1"
                shift
                ;;
            --type)
                shift
                CONFIG_TYPE="$1"
                shift
                ;;
            -h|--help)
                show_usage
                exit 0
                ;;
            *)
                if [[ "$command" == "shell" ]] || [[ "$command" == "exec" ]]; then
                    SPECIFIC_NODE="$1"
                    shift
                    if [[ "$command" == "exec" ]] && [[ $# -gt 0 ]]; then
                        # Remaining args are the command to execute
                        EXEC_COMMAND="$*"
                        break
                    fi
                elif [[ "$command" == "start" ]] || [[ "$command" == "stop" ]] || [[ "$command" == "isolate" ]] || [[ "$command" == "heal" ]]; then
                    # Optional node ID for these commands
                    if [[ "$1" =~ ^[0-9,]+$ ]]; then
                        SPECIFIC_NODE="$1"
                        shift
                    else
                        log_error "Unknown option: $1"
                        exit 1
                    fi
                elif [[ "$command" == "partition" ]]; then
                    # Partition specification required
                    if [[ "$1" =~ ^[0-9,]+$ ]]; then
                        SPECIFIC_NODE="$1"
                        shift
                    else
                        log_error "Invalid partition specification: $1"
                        exit 1
                    fi
                else
                    log_error "Unknown option: $1"
                    exit 1
                fi
                ;;
        esac
    done
    
    # Validate arguments
    if ! [[ "$NODES" =~ ^[0-9]+$ ]] || [[ "$NODES" -lt 1 ]]; then
        log_error "Invalid number of nodes: $NODES"
        exit 1
    fi
    
    # Validate prefix for security (no path traversal)
    if [[ "$PREFIX" =~ \.\.|/ ]]; then
        log_error "Invalid prefix: $PREFIX (cannot contain '..' or '/')"
        exit 1
    fi
    
    # Validate prefix characters (alphanumeric and basic symbols only)
    if ! [[ "$PREFIX" =~ ^[a-zA-Z0-9_-]+$ ]]; then
        log_error "Invalid prefix: $PREFIX (only alphanumeric, underscore, and hyphen allowed)"
        exit 1
    fi
    
    # Create work directory if it doesn't exist
    if [[ ! -d "$WORK_DIR" ]]; then
        mkdir -p "$WORK_DIR"
    fi
    
    WORK_DIR="$(cd "$WORK_DIR" && pwd)"  # Convert to absolute path
    
    # Execute command
    case "$command" in
        setup)
            setup_environment
            ;;
        start)
            start_nso_nodes
            ;;
        stop)
            stop_nso_nodes
            ;;
        cleanup)
            cleanup_environment
            ;;
        status)
            show_status
            ;;
        shell)
            if [[ -z "$SPECIFIC_NODE" ]]; then
                log_error "Node ID required for shell command"
                exit 1
            fi
            enter_namespace_shell "$SPECIFIC_NODE"
            ;;
        exec)
            if [[ -z "$SPECIFIC_NODE" ]] || [[ -z "${EXEC_COMMAND:-}" ]]; then
                log_error "Node ID and command required for exec"
                exit 1
            fi
            exec_in_namespace "$SPECIFIC_NODE" "$EXEC_COMMAND"
            ;;
        test)
            test_connectivity
            ;;
        isolate)
            if [[ -z "$SPECIFIC_NODE" ]]; then
                log_error "Node ID required for isolate command"
                exit 1
            fi
            isolate_node "$SPECIFIC_NODE"
            ;;
        partition)
            if [[ -z "$SPECIFIC_NODE" ]]; then
                log_error "Partition specification required (e.g., '1,2')"
                exit 1
            fi
            create_partition "$SPECIFIC_NODE"
            ;;
        heal)
            heal_partition "$SPECIFIC_NODE"
            ;;
        configure)
            run_configure_wizard
            ;;
        help)
            show_usage
            ;;
        *)
            log_error "Unknown command: $command"
            show_usage
            exit 1
            ;;
    esac
}

# Show current status
show_status() {
    log_info "Cluster Status:"
    echo "  Nodes: $NODES"
    echo "  Prefix: $PREFIX"
    echo "  Work Directory: $WORK_DIR"
    echo "  Cluster Name: $CLUSTER_NAME"
    echo "  Network Prefix: $NETWORK_PREFIX"
    echo "  Bridge Name: $BRIDGE_NAME"
    echo "  SSL Enabled: $SSL_ENABLED"
    echo ""
    
    # Check bridge status
    if ip link show "$BRIDGE_NAME" >/dev/null 2>&1; then
        echo -e "  Bridge: ${GREEN}UP${NC}"
        ip addr show "$BRIDGE_NAME" | grep -E "inet|UP"
    else
        echo -e "  Bridge: ${RED}DOWN${NC}"
    fi
    
    echo ""
    echo "  Namespaces:"
    for ((i=1; i<=NODES; i++)); do
        local netns="${PREFIX}${i}ns"
        if ip netns list | grep -q "^$netns"; then
            echo -e "    $netns: ${GREEN}EXISTS${NC}"
        else
            echo -e "    $netns: ${RED}MISSING${NC}"
        fi
    done
    
    echo ""
    show_nso_status
    
    echo ""
    show_partition_status
}

# Enter namespace shell
enter_namespace_shell() {
    local node_id="$1"
    local netns="${PREFIX}${node_id}ns"
    local env_source=$(get_nso_env_source)
    
    if ! ip netns list | grep -q "^$netns"; then
        log_error "Namespace $netns does not exist"
        exit 1
    fi
    
    log_info "Entering shell for namespace $netns"
    log_info "Use 'exit' to return to host shell"
    
    local user_name=$(id -un)
    local user_home=$(getent passwd "$user_name" | cut -d: -f6)
    local start_dir="$PWD"
    sudo ip netns exec "$netns" sudo -u "$user_name" bash --init-file <(echo "
        $env_source
        cd '$start_dir'
        export PS1='[$netns] \u@\h:\w$ '
        export NCS_IPC_ADDR=${NETWORK_PREFIX}.${node_id}.1
        echo 'Namespace: $netns'
        echo 'Node IP: ${NETWORK_PREFIX}.${node_id}.1'
        echo 'NSO Environment: ${ENV_SH_PATH:-not configured}'
        echo 'Available hosts:'
        cat /etc/hosts | grep ha-cluster
        echo 'NSO Commands available: ncs, ncs_cli, ncs_cmd'
    ")
}

# Execute command in namespace
exec_in_namespace() {
    local node_id="$1"
    local cmd="$2"
    local netns="${PREFIX}${node_id}ns"
    local env_source=$(get_nso_env_source)
    
    if ! ip netns list | grep -q "^$netns"; then
        log_error "Namespace $netns does not exist"
        exit 1
    fi
    
    log_debug "Executing in $netns: $cmd"
    
    local user_name=$(id -un)
    local start_dir="$PWD"
    sudo ip netns exec "$netns" sudo -u "$user_name" bash -c "
        $env_source
        cd '$start_dir'
        export NCS_IPC_ADDR=${NETWORK_PREFIX}.${node_id}.1
        $cmd
    "
}

# =============================================================================
# Configuration Generator Functions
# =============================================================================

# Default node names for auto-generation
DEFAULT_NODE_NAMES=("berlin" "london" "paris" "tokyo" "sydney" "newyork" "mumbai" "dublin" "singapore" "toronto")

# Default ASN base (will increment from here)
DEFAULT_ASN_BASE=64510

# Generate auto configuration
generate_auto_config() {
    local num_nodes="$1"
    local config_type="$2"
    local output_file="$3"
    
    log_info "Generating auto configuration for $num_nodes nodes (type: $config_type)"
    
    case "$config_type" in
        "simple")
            generate_simple_config "$num_nodes" "$output_file"
            ;;
        "l3bgp")
            generate_l3bgp_config "$num_nodes" "$output_file"
            ;;
        *)
            log_error "Unknown configuration type: $config_type"
            return 1
            ;;
    esac
}

# Generate simple configuration
generate_simple_config() {
    local num_nodes="$1"
    local output_file="$2"
    
    cat > "$output_file" << EOF
# RAFT Cluster Configuration - Simple Mode
# Generated automatically on $(date)

# Cluster settings
nodes=$num_nodes
cluster_name=auto-cluster
prefix=ha
work_dir=$(pwd)

# Network settings (simple mode)
network_prefix=192.168
bridge_name=ha-cluster

# NSO settings
ssl_enabled=false
ssl_cert_dir=
ncs_flags=
host=localhost.localdomain
env_sh_path=$(pwd)/env.sh

# Timeouts
timeout=30
EOF
    
    log_info "Generated simple configuration: $output_file"
}

# Generate L3 BGP configuration
generate_l3bgp_config() {
    local num_nodes="$1"
    local output_file="$2"
    
    cat > "$output_file" << EOF
# RAFT Cluster Configuration - Layer 3 BGP Topology
# Generated automatically on $(date)

# Basic cluster settings
nodes=$num_nodes
cluster_name=bgp-cluster
prefix=l3bgp
work_dir=$(pwd)

# Network topology type
network_type=l3bgp

# Manager node configuration
manager_enabled=true
manager_name=manager
manager_ip=172.17.0.2
manager_subnet=172.17.0.0/16
manager_asn=64500
manager_bridge=docker0

# BGP configuration
bgp_enabled=true
bgp_router_id_base=1.1.1

EOF

    # Generate node-specific configurations
    for ((i=1; i<=num_nodes; i++)); do
        local node_name="${DEFAULT_NODE_NAMES[$((i-1))]}"
        local node_asn=$((DEFAULT_ASN_BASE + i))
        local subnet_third=$((30 + i - 1))
        local host_last=$((96 + i))
        
        cat >> "$output_file" << EOF
# Node $i - ${node_name^}
node_${i}_name=$node_name
node_${i}_ip=192.168.$subnet_third.$host_last
node_${i}_subnet=192.168.$subnet_third.0/24
node_${i}_asn=$node_asn
node_${i}_hostname=$node_name.cluster.local

EOF
    done
    
    cat >> "$output_file" << EOF
# Inter-node connectivity
connect_manager_berlin=direct
connect_manager_london=direct
connect_manager_paris=direct
EOF

    # Add BGP peering connections
    for ((i=1; i<=num_nodes; i++)); do
        for ((j=i+1; j<=num_nodes; j++)); do
            local name1="${DEFAULT_NODE_NAMES[$((i-1))]}"
            local name2="${DEFAULT_NODE_NAMES[$((j-1))]}"
            echo "connect_${name1}_${name2}=bgp_peering" >> "$output_file"
        done
    done
    
    cat >> "$output_file" << EOF

# NSO settings
ssl_enabled=false
ssl_cert_dir=
ncs_flags=
host=localhost.localdomain
env_sh_path=$(pwd)/env.sh

# Timeouts
timeout=30
EOF
    
    log_info "Generated L3 BGP configuration: $output_file"
}

# Interactive configuration wizard
run_configure_wizard() {
    echo ""
    echo -e "${GREEN}=== RAFT Cluster Configuration Wizard ===${NC}"
    echo ""
    
    # Determine output file
    local output_file="${CONFIG_OUTPUT}"
    if [[ -z "$output_file" ]]; then
        read -p "Configuration file name [.raft-cluster.conf]: " output_file
        output_file="${output_file:-.raft-cluster.conf}"
    fi
    
    # Check if file exists
    if [[ -f "$output_file" ]] && [[ "$FORCE" != "true" ]]; then
        echo -e "${YELLOW}Warning: File $output_file already exists${NC}"
        read -p "Overwrite? (y/N): " confirm
        if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
            log_info "Configuration cancelled"
            return 0
        fi
    fi
    
    if [[ "$AUTO_GENERATE" == "true" ]]; then
        # Auto-generation mode
        local num_nodes="${NODES:-3}"
        if [[ -z "$NODES" ]]; then
            read -p "Number of nodes [3]: " num_nodes
            num_nodes="${num_nodes:-3}"
        fi
        
        echo "Configuration type options:"
        echo "  simple - Traditional flat network (current default)"
        echo "  l3bgp  - Layer 3 BGP with custom subnets and ASNs"
        echo ""
        local config_type="$CONFIG_TYPE"
        if [[ "$config_type" == "simple" ]]; then
            read -p "Configuration type [simple]: " config_type
            config_type="${config_type:-simple}"
        fi
        
        generate_auto_config "$num_nodes" "$config_type" "$output_file"
        
    else
        # Interactive mode
        run_interactive_config "$output_file"
    fi
    
    echo ""
    echo -e "${GREEN}Configuration created: $output_file${NC}"
    echo ""
    echo "Next steps:"
    echo "  1. Review and customize the configuration if needed"
    echo "  2. Run: $(basename "$0") setup -c $output_file"
    echo ""
}

# Interactive configuration
run_interactive_config() {
    local output_file="$1"
    
    echo "Let's create your RAFT cluster configuration..."
    echo ""
    
    # Basic settings
    read -p "Number of nodes [3]: " num_nodes
    num_nodes="${num_nodes:-3}"
    
    read -p "Cluster name [raft-cluster]: " cluster_name
    cluster_name="${cluster_name:-raft-cluster}"
    
    read -p "Namespace prefix [ha]: " prefix
    prefix="${prefix:-ha}"
    
    echo ""
    echo "Configuration type options:"
    echo "  1) simple - Traditional flat network"
    echo "  2) l3bgp  - Layer 3 BGP with custom topologies"
    echo ""
    read -p "Choose configuration type [1]: " type_choice
    type_choice="${type_choice:-1}"
    
    local config_type="simple"
    if [[ "$type_choice" == "2" ]]; then
        config_type="l3bgp"
    fi
    
    if [[ "$config_type" == "simple" ]]; then
        create_interactive_simple_config "$output_file" "$num_nodes" "$cluster_name" "$prefix"
    else
        create_interactive_l3bgp_config "$output_file" "$num_nodes" "$cluster_name" "$prefix"
    fi
}

# Create interactive simple config
create_interactive_simple_config() {
    local output_file="$1"
    local num_nodes="$2"
    local cluster_name="$3"
    local prefix="$4"
    
    read -p "Network prefix [192.168]: " network_prefix
    network_prefix="${network_prefix:-192.168}"
    
    read -p "Bridge name [${prefix}-cluster]: " bridge_name
    bridge_name="${bridge_name:-${prefix}-cluster}"
    
    cat > "$output_file" << EOF
# RAFT Cluster Configuration - Simple Mode
# Created interactively on $(date)

# Cluster settings
nodes=$num_nodes
cluster_name=$cluster_name
prefix=$prefix
work_dir=$(pwd)

# Network settings
network_prefix=$network_prefix
bridge_name=$bridge_name

# NSO settings
ssl_enabled=false
ssl_cert_dir=
ncs_flags=
host=localhost.localdomain
env_sh_path=$(pwd)/env.sh

# Timeouts
timeout=30
EOF
}

# Create interactive L3 BGP config
create_interactive_l3bgp_config() {
    local output_file="$1"
    local num_nodes="$2"
    local cluster_name="$3"
    local prefix="$4"
    
    echo ""
    echo "=== Layer 3 BGP Configuration ==="
    echo ""
    
    read -p "Enable manager node for route reflection? [Y/n]: " enable_manager
    enable_manager="${enable_manager:-Y}"
    
    local manager_enabled="false"
    if [[ "$enable_manager" == "Y" || "$enable_manager" == "y" ]]; then
        manager_enabled="true"
    fi
    
    # Start with basic L3BGP template
    cat > "$output_file" << EOF
# RAFT Cluster Configuration - Layer 3 BGP Topology
# Created interactively on $(date)

# Basic cluster settings
nodes=$num_nodes
cluster_name=$cluster_name
prefix=$prefix
work_dir=$(pwd)

# Network topology type
network_type=l3bgp

# Manager node configuration
manager_enabled=$manager_enabled
EOF

    if [[ "$manager_enabled" == "true" ]]; then
        read -p "Manager IP [172.17.0.2]: " manager_ip
        manager_ip="${manager_ip:-172.17.0.2}"
        
        read -p "Manager ASN [64500]: " manager_asn
        manager_asn="${manager_asn:-64500}"
        
        cat >> "$output_file" << EOF
manager_name=manager
manager_ip=$manager_ip
manager_subnet=172.17.0.0/16
manager_asn=$manager_asn
manager_bridge=docker0

EOF
    fi
    
    cat >> "$output_file" << EOF
# BGP configuration
bgp_enabled=true
bgp_router_id_base=1.1.1

EOF
    
    # Configure each node
    echo ""
    echo "Now let's configure each node..."
    for ((i=1; i<=num_nodes; i++)); do
        echo ""
        echo "--- Node $i ---"
        
        local default_name="${DEFAULT_NODE_NAMES[$((i-1))]}"
        read -p "Node $i name [$default_name]: " node_name
        node_name="${node_name:-$default_name}"
        
        local default_asn=$((DEFAULT_ASN_BASE + i))
        read -p "Node $i ASN [$default_asn]: " node_asn
        node_asn="${node_asn:-$default_asn}"
        
        local default_subnet=$((30 + i - 1))
        local default_ip=$((96 + i))
        read -p "Node $i subnet [192.168.$default_subnet.0/24]: " node_subnet
        node_subnet="${node_subnet:-192.168.$default_subnet.0/24}"
        
        read -p "Node $i IP [192.168.$default_subnet.$default_ip]: " node_ip
        node_ip="${node_ip:-192.168.$default_subnet.$default_ip}"
        
        cat >> "$output_file" << EOF
# Node $i - ${node_name^}
node_${i}_name=$node_name
node_${i}_ip=$node_ip
node_${i}_subnet=$node_subnet
node_${i}_asn=$node_asn
node_${i}_hostname=$node_name.cluster.local

EOF
    done
    
    # Add remaining config
    cat >> "$output_file" << EOF
# NSO settings
ssl_enabled=false
ssl_cert_dir=
ncs_flags=
host=localhost.localdomain
env_sh_path=$(pwd)/env.sh

# Timeouts
timeout=30
EOF
    
    echo ""
    echo -e "${GREEN}L3 BGP configuration created!${NC}"
}

# Trap handler for cleanup on exit
cleanup_on_exit() {
    local exit_code=$?
    # Only show warning for actual failures (not normal exit or user interruption)
    if [[ $exit_code -ne 0 ]] && [[ $exit_code -ne 130 ]] && [[ "${DRY_RUN}" != "true" ]]; then
        log_warn "Script failed, you may need to run 'cleanup' manually"
    fi
    exit $exit_code
}

# Set trap for cleanup
trap cleanup_on_exit INT TERM

# Main entry point
main() {
    parse_args "$@"
}

# Only run main if script is executed directly (not sourced)
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
